# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uimain.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 900)
        MainWindow.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_title = QtWidgets.QLabel(self.centralwidget)
        self.lb_title.setGeometry(QtCore.QRect(10, 20, 981, 41))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lb_title.setFont(font)
        self.lb_title.setStyleSheet("")
        self.lb_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_title.setObjectName("lb_title")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 150, 121, 22))
        self.comboBox.setStyleSheet("font: 9pt \"IBM Plex Mono\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lb_subtitle = QtWidgets.QLabel(self.centralwidget)
        self.lb_subtitle.setGeometry(QtCore.QRect(10, 80, 981, 41))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lb_subtitle.setFont(font)
        self.lb_subtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_subtitle.setObjectName("lb_subtitle")
        self.lb_com = QtWidgets.QLabel(self.centralwidget)
        self.lb_com.setGeometry(QtCore.QRect(10, 130, 121, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_com.setFont(font)
        self.lb_com.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_com.setObjectName("lb_com")
        self.lb_freq = QtWidgets.QLabel(self.centralwidget)
        self.lb_freq.setGeometry(QtCore.QRect(10, 180, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_freq.setFont(font)
        self.lb_freq.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_freq.setObjectName("lb_freq")
        self.val_freq = QtWidgets.QLabel(self.centralwidget)
        self.val_freq.setGeometry(QtCore.QRect(10, 200, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_freq.setFont(font)
        self.val_freq.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_freq.setObjectName("val_freq")
        self.lb_pkg = QtWidgets.QLabel(self.centralwidget)
        self.lb_pkg.setGeometry(QtCore.QRect(150, 130, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_pkg.setFont(font)
        self.lb_pkg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_pkg.setObjectName("lb_pkg")
        self.val_pkg = QtWidgets.QLabel(self.centralwidget)
        self.val_pkg.setGeometry(QtCore.QRect(150, 150, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_pkg.setFont(font)
        self.val_pkg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_pkg.setObjectName("val_pkg")
        self.val_sys_time = QtWidgets.QLabel(self.centralwidget)
        self.val_sys_time.setGeometry(QtCore.QRect(290, 150, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_sys_time.setFont(font)
        self.val_sys_time.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_sys_time.setObjectName("val_sys_time")
        self.lb_sys_time = QtWidgets.QLabel(self.centralwidget)
        self.lb_sys_time.setGeometry(QtCore.QRect(290, 130, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_sys_time.setFont(font)
        self.lb_sys_time.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_sys_time.setObjectName("lb_sys_time")
        self.val_lat = QtWidgets.QLabel(self.centralwidget)
        self.val_lat.setGeometry(QtCore.QRect(430, 150, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_lat.setFont(font)
        self.val_lat.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_lat.setObjectName("val_lat")
        self.lb_lat = QtWidgets.QLabel(self.centralwidget)
        self.lb_lat.setGeometry(QtCore.QRect(430, 130, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_lat.setFont(font)
        self.lb_lat.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_lat.setObjectName("lb_lat")
        self.val_lon = QtWidgets.QLabel(self.centralwidget)
        self.val_lon.setGeometry(QtCore.QRect(570, 150, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_lon.setFont(font)
        self.val_lon.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_lon.setObjectName("val_lon")
        self.lb_lon = QtWidgets.QLabel(self.centralwidget)
        self.lb_lon.setGeometry(QtCore.QRect(570, 130, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_lon.setFont(font)
        self.lb_lon.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_lon.setObjectName("lb_lon")
        self.val_gps_alt = QtWidgets.QLabel(self.centralwidget)
        self.val_gps_alt.setGeometry(QtCore.QRect(710, 150, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_gps_alt.setFont(font)
        self.val_gps_alt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_gps_alt.setObjectName("val_gps_alt")
        self.lb_gps_alt = QtWidgets.QLabel(self.centralwidget)
        self.lb_gps_alt.setGeometry(QtCore.QRect(710, 130, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_gps_alt.setFont(font)
        self.lb_gps_alt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_gps_alt.setObjectName("lb_gps_alt")
        self.lb_int_temp = QtWidgets.QLabel(self.centralwidget)
        self.lb_int_temp.setGeometry(QtCore.QRect(150, 180, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_int_temp.setFont(font)
        self.lb_int_temp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_int_temp.setObjectName("lb_int_temp")
        self.val_ext_temp = QtWidgets.QLabel(self.centralwidget)
        self.val_ext_temp.setGeometry(QtCore.QRect(290, 200, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_ext_temp.setFont(font)
        self.val_ext_temp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_ext_temp.setObjectName("val_ext_temp")
        self.val_int_temp = QtWidgets.QLabel(self.centralwidget)
        self.val_int_temp.setGeometry(QtCore.QRect(150, 200, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_int_temp.setFont(font)
        self.val_int_temp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_int_temp.setObjectName("val_int_temp")
        self.val_vel = QtWidgets.QLabel(self.centralwidget)
        self.val_vel.setGeometry(QtCore.QRect(570, 200, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_vel.setFont(font)
        self.val_vel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_vel.setObjectName("val_vel")
        self.lb_vel = QtWidgets.QLabel(self.centralwidget)
        self.lb_vel.setGeometry(QtCore.QRect(570, 180, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_vel.setFont(font)
        self.lb_vel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_vel.setObjectName("lb_vel")
        self.val_hum = QtWidgets.QLabel(self.centralwidget)
        self.val_hum.setGeometry(QtCore.QRect(430, 200, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_hum.setFont(font)
        self.val_hum.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_hum.setObjectName("val_hum")
        self.lb_bar_alt = QtWidgets.QLabel(self.centralwidget)
        self.lb_bar_alt.setGeometry(QtCore.QRect(710, 180, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_bar_alt.setFont(font)
        self.lb_bar_alt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_bar_alt.setObjectName("lb_bar_alt")
        self.lb_hum = QtWidgets.QLabel(self.centralwidget)
        self.lb_hum.setGeometry(QtCore.QRect(430, 180, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_hum.setFont(font)
        self.lb_hum.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_hum.setObjectName("lb_hum")
        self.lb_ext_temp = QtWidgets.QLabel(self.centralwidget)
        self.lb_ext_temp.setGeometry(QtCore.QRect(290, 180, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_ext_temp.setFont(font)
        self.lb_ext_temp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_ext_temp.setObjectName("lb_ext_temp")
        self.val_bar_alt = QtWidgets.QLabel(self.centralwidget)
        self.val_bar_alt.setGeometry(QtCore.QRect(710, 200, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_bar_alt.setFont(font)
        self.val_bar_alt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_bar_alt.setObjectName("val_bar_alt")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(880, 100, 121, 31))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(85, 85, 85);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(880, 150, 121, 31))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(85, 85, 85);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(880, 200, 121, 31))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(85, 85, 85);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.val_accx = QtWidgets.QLabel(self.centralwidget)
        self.val_accx.setGeometry(QtCore.QRect(10, 250, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_accx.setFont(font)
        self.val_accx.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_accx.setObjectName("val_accx")
        self.lb_accz = QtWidgets.QLabel(self.centralwidget)
        self.lb_accz.setGeometry(QtCore.QRect(290, 230, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_accz.setFont(font)
        self.lb_accz.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_accz.setObjectName("lb_accz")
        self.val_gyrx = QtWidgets.QLabel(self.centralwidget)
        self.val_gyrx.setGeometry(QtCore.QRect(430, 250, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_gyrx.setFont(font)
        self.val_gyrx.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_gyrx.setObjectName("val_gyrx")
        self.lb_gyrx = QtWidgets.QLabel(self.centralwidget)
        self.lb_gyrx.setGeometry(QtCore.QRect(430, 230, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_gyrx.setFont(font)
        self.lb_gyrx.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_gyrx.setObjectName("lb_gyrx")
        self.val_accz = QtWidgets.QLabel(self.centralwidget)
        self.val_accz.setGeometry(QtCore.QRect(290, 250, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_accz.setFont(font)
        self.val_accz.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_accz.setObjectName("val_accz")
        self.lb_accx = QtWidgets.QLabel(self.centralwidget)
        self.lb_accx.setGeometry(QtCore.QRect(10, 230, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_accx.setFont(font)
        self.lb_accx.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_accx.setObjectName("lb_accx")
        self.lb_gyry = QtWidgets.QLabel(self.centralwidget)
        self.lb_gyry.setGeometry(QtCore.QRect(570, 230, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_gyry.setFont(font)
        self.lb_gyry.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_gyry.setObjectName("lb_gyry")
        self.lb_accy = QtWidgets.QLabel(self.centralwidget)
        self.lb_accy.setGeometry(QtCore.QRect(150, 230, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_accy.setFont(font)
        self.lb_accy.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_accy.setObjectName("lb_accy")
        self.val_gyry = QtWidgets.QLabel(self.centralwidget)
        self.val_gyry.setGeometry(QtCore.QRect(570, 250, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_gyry.setFont(font)
        self.val_gyry.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_gyry.setObjectName("val_gyry")
        self.lb_gyrz = QtWidgets.QLabel(self.centralwidget)
        self.lb_gyrz.setGeometry(QtCore.QRect(710, 230, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_gyrz.setFont(font)
        self.lb_gyrz.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_gyrz.setObjectName("lb_gyrz")
        self.val_accy = QtWidgets.QLabel(self.centralwidget)
        self.val_accy.setGeometry(QtCore.QRect(150, 250, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_accy.setFont(font)
        self.val_accy.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_accy.setObjectName("val_accy")
        self.val_gyrz = QtWidgets.QLabel(self.centralwidget)
        self.val_gyrz.setGeometry(QtCore.QRect(710, 250, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_gyrz.setFont(font)
        self.val_gyrz.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_gyrz.setObjectName("val_gyrz")
        self.lb_subtitle_2 = QtWidgets.QLabel(self.centralwidget)
        self.lb_subtitle_2.setGeometry(QtCore.QRect(10, 280, 981, 41))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lb_subtitle_2.setFont(font)
        self.lb_subtitle_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_subtitle_2.setObjectName("lb_subtitle_2")
        self.val_pkg_2 = QtWidgets.QLabel(self.centralwidget)
        self.val_pkg_2.setGeometry(QtCore.QRect(150, 350, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_pkg_2.setFont(font)
        self.val_pkg_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_pkg_2.setObjectName("val_pkg_2")
        self.lb_pkg_2 = QtWidgets.QLabel(self.centralwidget)
        self.lb_pkg_2.setGeometry(QtCore.QRect(150, 330, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_pkg_2.setFont(font)
        self.lb_pkg_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_pkg_2.setObjectName("lb_pkg_2")
        self.lb_sys_time_2 = QtWidgets.QLabel(self.centralwidget)
        self.lb_sys_time_2.setGeometry(QtCore.QRect(290, 330, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_sys_time_2.setFont(font)
        self.lb_sys_time_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_sys_time_2.setObjectName("lb_sys_time_2")
        self.val_sys_time_2 = QtWidgets.QLabel(self.centralwidget)
        self.val_sys_time_2.setGeometry(QtCore.QRect(290, 350, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_sys_time_2.setFont(font)
        self.val_sys_time_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_sys_time_2.setObjectName("val_sys_time_2")
        self.lb_lon_2 = QtWidgets.QLabel(self.centralwidget)
        self.lb_lon_2.setGeometry(QtCore.QRect(570, 330, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_lon_2.setFont(font)
        self.lb_lon_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_lon_2.setObjectName("lb_lon_2")
        self.val_lon_2 = QtWidgets.QLabel(self.centralwidget)
        self.val_lon_2.setGeometry(QtCore.QRect(570, 350, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_lon_2.setFont(font)
        self.val_lon_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_lon_2.setObjectName("val_lon_2")
        self.val_lat_2 = QtWidgets.QLabel(self.centralwidget)
        self.val_lat_2.setGeometry(QtCore.QRect(430, 350, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_lat_2.setFont(font)
        self.val_lat_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_lat_2.setObjectName("val_lat_2")
        self.lb_lat_2 = QtWidgets.QLabel(self.centralwidget)
        self.lb_lat_2.setGeometry(QtCore.QRect(430, 330, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_lat_2.setFont(font)
        self.lb_lat_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_lat_2.setObjectName("lb_lat_2")
        self.lb_pm103 = QtWidgets.QLabel(self.centralwidget)
        self.lb_pm103.setGeometry(QtCore.QRect(290, 380, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_pm103.setFont(font)
        self.lb_pm103.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_pm103.setObjectName("lb_pm103")
        self.val_pm101 = QtWidgets.QLabel(self.centralwidget)
        self.val_pm101.setGeometry(QtCore.QRect(10, 400, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_pm101.setFont(font)
        self.val_pm101.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_pm101.setObjectName("val_pm101")
        self.lb_pm102 = QtWidgets.QLabel(self.centralwidget)
        self.lb_pm102.setGeometry(QtCore.QRect(150, 380, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_pm102.setFont(font)
        self.lb_pm102.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_pm102.setObjectName("lb_pm102")
        self.val_pm103 = QtWidgets.QLabel(self.centralwidget)
        self.val_pm103.setGeometry(QtCore.QRect(290, 400, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_pm103.setFont(font)
        self.val_pm103.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_pm103.setObjectName("val_pm103")
        self.val_102 = QtWidgets.QLabel(self.centralwidget)
        self.val_102.setGeometry(QtCore.QRect(150, 400, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_102.setFont(font)
        self.val_102.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_102.setObjectName("val_102")
        self.lb_pm101 = QtWidgets.QLabel(self.centralwidget)
        self.lb_pm101.setGeometry(QtCore.QRect(10, 380, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_pm101.setFont(font)
        self.lb_pm101.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_pm101.setObjectName("lb_pm101")
        self.lb_ext_temp_2 = QtWidgets.QLabel(self.centralwidget)
        self.lb_ext_temp_2.setGeometry(QtCore.QRect(710, 330, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_ext_temp_2.setFont(font)
        self.lb_ext_temp_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_ext_temp_2.setObjectName("lb_ext_temp_2")
        self.val_ext_temp_2 = QtWidgets.QLabel(self.centralwidget)
        self.val_ext_temp_2.setGeometry(QtCore.QRect(710, 350, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_ext_temp_2.setFont(font)
        self.val_ext_temp_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_ext_temp_2.setObjectName("val_ext_temp_2")
        self.lb_subtitle_3 = QtWidgets.QLabel(self.centralwidget)
        self.lb_subtitle_3.setGeometry(QtCore.QRect(10, 430, 981, 41))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lb_subtitle_3.setFont(font)
        self.lb_subtitle_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_subtitle_3.setObjectName("lb_subtitle_3")
        self.lb_pkg_3 = QtWidgets.QLabel(self.centralwidget)
        self.lb_pkg_3.setGeometry(QtCore.QRect(150, 480, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_pkg_3.setFont(font)
        self.lb_pkg_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_pkg_3.setObjectName("lb_pkg_3")
        self.val_pkg_3 = QtWidgets.QLabel(self.centralwidget)
        self.val_pkg_3.setGeometry(QtCore.QRect(150, 500, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_pkg_3.setFont(font)
        self.val_pkg_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_pkg_3.setObjectName("val_pkg_3")
        self.lb_sys_time_3 = QtWidgets.QLabel(self.centralwidget)
        self.lb_sys_time_3.setGeometry(QtCore.QRect(290, 480, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_sys_time_3.setFont(font)
        self.lb_sys_time_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_sys_time_3.setObjectName("lb_sys_time_3")
        self.val_sys_time_3 = QtWidgets.QLabel(self.centralwidget)
        self.val_sys_time_3.setGeometry(QtCore.QRect(290, 500, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_sys_time_3.setFont(font)
        self.val_sys_time_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_sys_time_3.setObjectName("val_sys_time_3")
        self.lb_gps_alt_2 = QtWidgets.QLabel(self.centralwidget)
        self.lb_gps_alt_2.setGeometry(QtCore.QRect(430, 480, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_gps_alt_2.setFont(font)
        self.lb_gps_alt_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_gps_alt_2.setObjectName("lb_gps_alt_2")
        self.val_gps_alt_2 = QtWidgets.QLabel(self.centralwidget)
        self.val_gps_alt_2.setGeometry(QtCore.QRect(430, 500, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_gps_alt_2.setFont(font)
        self.val_gps_alt_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_gps_alt_2.setObjectName("val_gps_alt_2")
        self.lb_bar_alt_2 = QtWidgets.QLabel(self.centralwidget)
        self.lb_bar_alt_2.setGeometry(QtCore.QRect(570, 480, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_bar_alt_2.setFont(font)
        self.lb_bar_alt_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_bar_alt_2.setObjectName("lb_bar_alt_2")
        self.val_bar_alt_2 = QtWidgets.QLabel(self.centralwidget)
        self.val_bar_alt_2.setGeometry(QtCore.QRect(570, 500, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_bar_alt_2.setFont(font)
        self.val_bar_alt_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_bar_alt_2.setObjectName("val_bar_alt_2")
        self.lb_vol = QtWidgets.QLabel(self.centralwidget)
        self.lb_vol.setGeometry(QtCore.QRect(710, 480, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_vol.setFont(font)
        self.lb_vol.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_vol.setObjectName("lb_vol")
        self.val_vol = QtWidgets.QLabel(self.centralwidget)
        self.val_vol.setGeometry(QtCore.QRect(710, 500, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_vol.setFont(font)
        self.val_vol.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_vol.setObjectName("val_vol")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(880, 250, 121, 31))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(85, 85, 85);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.val_freq_2 = QtWidgets.QLabel(self.centralwidget)
        self.val_freq_2.setGeometry(QtCore.QRect(10, 350, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_freq_2.setFont(font)
        self.val_freq_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_freq_2.setObjectName("val_freq_2")
        self.lb_freq_2 = QtWidgets.QLabel(self.centralwidget)
        self.lb_freq_2.setGeometry(QtCore.QRect(10, 330, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_freq_2.setFont(font)
        self.lb_freq_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_freq_2.setObjectName("lb_freq_2")
        self.val_freq_3 = QtWidgets.QLabel(self.centralwidget)
        self.val_freq_3.setGeometry(QtCore.QRect(10, 500, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_freq_3.setFont(font)
        self.val_freq_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_freq_3.setObjectName("val_freq_3")
        self.lb_freq_3 = QtWidgets.QLabel(self.centralwidget)
        self.lb_freq_3.setGeometry(QtCore.QRect(10, 480, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_freq_3.setFont(font)
        self.lb_freq_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_freq_3.setObjectName("lb_freq_3")
        self.val_lon_3 = QtWidgets.QLabel(self.centralwidget)
        self.val_lon_3.setGeometry(QtCore.QRect(150, 550, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_lon_3.setFont(font)
        self.val_lon_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_lon_3.setObjectName("val_lon_3")
        self.lb_lat_3 = QtWidgets.QLabel(self.centralwidget)
        self.lb_lat_3.setGeometry(QtCore.QRect(10, 530, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_lat_3.setFont(font)
        self.lb_lat_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_lat_3.setObjectName("lb_lat_3")
        self.lb_lon_3 = QtWidgets.QLabel(self.centralwidget)
        self.lb_lon_3.setGeometry(QtCore.QRect(150, 530, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_lon_3.setFont(font)
        self.lb_lon_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_lon_3.setObjectName("lb_lon_3")
        self.val_lat_3 = QtWidgets.QLabel(self.centralwidget)
        self.val_lat_3.setGeometry(QtCore.QRect(10, 550, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_lat_3.setFont(font)
        self.val_lat_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_lat_3.setObjectName("val_lat_3")
        self.val_sys_time_4 = QtWidgets.QLabel(self.centralwidget)
        self.val_sys_time_4.setGeometry(QtCore.QRect(490, 700, 451, 51))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.val_sys_time_4.setFont(font)
        self.val_sys_time_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.val_sys_time_4.setObjectName("val_sys_time_4")
        self.lb_sys_time_4 = QtWidgets.QLabel(self.centralwidget)
        self.lb_sys_time_4.setGeometry(QtCore.QRect(630, 670, 311, 21))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lb_sys_time_4.setFont(font)
        self.lb_sys_time_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_sys_time_4.setObjectName("lb_sys_time_4")
        self.val_sys_time_5 = QtWidgets.QLabel(self.centralwidget)
        self.val_sys_time_5.setGeometry(QtCore.QRect(50, 700, 421, 51))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.val_sys_time_5.setFont(font)
        self.val_sys_time_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_sys_time_5.setObjectName("val_sys_time_5")
        self.lb_sys_time_5 = QtWidgets.QLabel(self.centralwidget)
        self.lb_sys_time_5.setGeometry(QtCore.QRect(50, 670, 321, 21))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lb_sys_time_5.setFont(font)
        self.lb_sys_time_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_sys_time_5.setObjectName("lb_sys_time_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(880, 300, 121, 31))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(85, 85, 85);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(880, 350, 121, 31))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(85, 85, 85);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(880, 400, 121, 31))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(12)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(85, 85, 85);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(880, 450, 121, 31))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(12)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: rgb(85, 85, 85);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(880, 500, 121, 31))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(12)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: rgb(85, 85, 85);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(880, 550, 121, 31))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(12)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("background-color: rgb(85, 85, 85);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.lb_lon_4 = QtWidgets.QLabel(self.centralwidget)
        self.lb_lon_4.setGeometry(QtCore.QRect(150, 600, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_lon_4.setFont(font)
        self.lb_lon_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_lon_4.setObjectName("lb_lon_4")
        self.val_lon_4 = QtWidgets.QLabel(self.centralwidget)
        self.val_lon_4.setGeometry(QtCore.QRect(150, 620, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_lon_4.setFont(font)
        self.val_lon_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_lon_4.setObjectName("val_lon_4")
        self.val_lat_4 = QtWidgets.QLabel(self.centralwidget)
        self.val_lat_4.setGeometry(QtCore.QRect(10, 620, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_lat_4.setFont(font)
        self.val_lat_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_lat_4.setObjectName("val_lat_4")
        self.lb_lat_4 = QtWidgets.QLabel(self.centralwidget)
        self.lb_lat_4.setGeometry(QtCore.QRect(10, 600, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_lat_4.setFont(font)
        self.lb_lat_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_lat_4.setObjectName("lb_lat_4")
        self.R2 = QtWidgets.QProgressBar(self.centralwidget)
        self.R2.setGeometry(QtCore.QRect(660, 580, 171, 21))
        self.R2.setStyleSheet("QProgressBar {\n"
"    \n"
"    background-color: rgb(40, 40 , 40);\n"
"    border-style: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(219, 0, 0);\n"
"}")
        self.R2.setProperty("value", 24)
        self.R2.setObjectName("R2")
        self.lb_adjroll = QtWidgets.QLabel(self.centralwidget)
        self.lb_adjroll.setGeometry(QtCore.QRect(350, 580, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_adjroll.setFont(font)
        self.lb_adjroll.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_adjroll.setObjectName("lb_adjroll")
        self.lb_adjalt = QtWidgets.QLabel(self.centralwidget)
        self.lb_adjalt.setGeometry(QtCore.QRect(350, 600, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_adjalt.setFont(font)
        self.lb_adjalt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_adjalt.setObjectName("lb_adjalt")
        self.lb_adjplane = QtWidgets.QLabel(self.centralwidget)
        self.lb_adjplane.setGeometry(QtCore.QRect(350, 620, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_adjplane.setFont(font)
        self.lb_adjplane.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_adjplane.setObjectName("lb_adjplane")
        self.R1 = QtWidgets.QProgressBar(self.centralwidget)
        self.R1.setGeometry(QtCore.QRect(490, 580, 171, 21))
        self.R1.setStyleSheet("QProgressBar {\n"
"    \n"
"    background-color: rgb(219, 0, 0);\n"
"    border-style: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(40, 40, 40);\n"
"}")
        self.R1.setProperty("value", 24)
        self.R1.setObjectName("R1")
        self.A1 = QtWidgets.QProgressBar(self.centralwidget)
        self.A1.setGeometry(QtCore.QRect(490, 600, 171, 20))
        self.A1.setStyleSheet("QProgressBar {\n"
"    \n"
"    background-color: rgb(219, 0, 0);\n"
"    border-style: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(40, 40, 40);\n"
"}")
        self.A1.setProperty("value", 24)
        self.A1.setObjectName("A1")
        self.P1 = QtWidgets.QProgressBar(self.centralwidget)
        self.P1.setGeometry(QtCore.QRect(490, 620, 171, 20))
        self.P1.setStyleSheet("QProgressBar {\n"
"    \n"
"    background-color: rgb(219, 0, 0);\n"
"    border-style: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(40, 40, 40);\n"
"}")
        self.P1.setProperty("value", 24)
        self.P1.setObjectName("P1")
        self.A2 = QtWidgets.QProgressBar(self.centralwidget)
        self.A2.setGeometry(QtCore.QRect(660, 600, 171, 21))
        self.A2.setStyleSheet("QProgressBar {\n"
"    \n"
"    background-color: rgb(40, 40 , 40);\n"
"    border-style: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(219, 0, 0);\n"
"}")
        self.A2.setProperty("value", 24)
        self.A2.setObjectName("A2")
        self.P2 = QtWidgets.QProgressBar(self.centralwidget)
        self.P2.setGeometry(QtCore.QRect(660, 620, 171, 21))
        self.P2.setStyleSheet("QProgressBar {\n"
"    \n"
"    background-color: rgb(40, 40 , 40);\n"
"    border-style: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(219, 0, 0);\n"
"}")
        self.P2.setProperty("value", 24)
        self.P2.setObjectName("P2")
        self.lb_sys_time_6 = QtWidgets.QLabel(self.centralwidget)
        self.lb_sys_time_6.setGeometry(QtCore.QRect(50, 780, 321, 21))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lb_sys_time_6.setFont(font)
        self.lb_sys_time_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_sys_time_6.setObjectName("lb_sys_time_6")
        self.lb_sys_time_7 = QtWidgets.QLabel(self.centralwidget)
        self.lb_sys_time_7.setGeometry(QtCore.QRect(630, 780, 311, 21))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lb_sys_time_7.setFont(font)
        self.lb_sys_time_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_sys_time_7.setObjectName("lb_sys_time_7")
        self.val_xlos = QtWidgets.QLabel(self.centralwidget)
        self.val_xlos.setGeometry(QtCore.QRect(490, 810, 451, 51))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.val_xlos.setFont(font)
        self.val_xlos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.val_xlos.setObjectName("val_xlos")
        self.val_xgd = QtWidgets.QLabel(self.centralwidget)
        self.val_xgd.setGeometry(QtCore.QRect(50, 810, 421, 51))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.val_xgd.setFont(font)
        self.val_xgd.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_xgd.setObjectName("val_xgd")
        self.val_gaz = QtWidgets.QLabel(self.centralwidget)
        self.val_gaz.setGeometry(QtCore.QRect(1040, 120, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_gaz.setFont(font)
        self.val_gaz.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_gaz.setObjectName("val_gaz")
        self.lb_vol_2 = QtWidgets.QLabel(self.centralwidget)
        self.lb_vol_2.setGeometry(QtCore.QRect(1040, 100, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_vol_2.setFont(font)
        self.lb_vol_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_vol_2.setObjectName("lb_vol_2")
        self.val_gel = QtWidgets.QLabel(self.centralwidget)
        self.val_gel.setGeometry(QtCore.QRect(1040, 170, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_gel.setFont(font)
        self.val_gel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_gel.setObjectName("val_gel")
        self.lb_vol_3 = QtWidgets.QLabel(self.centralwidget)
        self.lb_vol_3.setGeometry(QtCore.QRect(1040, 150, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_vol_3.setFont(font)
        self.lb_vol_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_vol_3.setObjectName("lb_vol_3")
        self.val_ghd = QtWidgets.QLabel(self.centralwidget)
        self.val_ghd.setGeometry(QtCore.QRect(1040, 220, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.val_ghd.setFont(font)
        self.val_ghd.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.val_ghd.setObjectName("val_ghd")
        self.lb_vol_4 = QtWidgets.QLabel(self.centralwidget)
        self.lb_vol_4.setGeometry(QtCore.QRect(1040, 200, 131, 16))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lb_vol_4.setFont(font)
        self.lb_vol_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_vol_4.setObjectName("lb_vol_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_title.setText(_translate("MainWindow", "PASSENGER-I GCS"))
        self.comboBox.setItemText(0, _translate("MainWindow", "COM PORTS"))
        self.comboBox.setItemText(1, _translate("MainWindow", "COM PORT 2"))
        self.lb_subtitle.setText(_translate("MainWindow", "CHANNEL 1 (433 MHz), BAUD 9600 ONLY!"))
        self.lb_com.setText(_translate("MainWindow", "SERIAL COM PORT"))
        self.lb_freq.setText(_translate("MainWindow", "FREQUENCY (MHz)"))
        self.val_freq.setText(_translate("MainWindow", "433"))
        self.lb_pkg.setText(_translate("MainWindow", "PACKET COUNT"))
        self.val_pkg.setText(_translate("MainWindow", "123"))
        self.val_sys_time.setText(_translate("MainWindow", "10:24:39"))
        self.lb_sys_time.setText(_translate("MainWindow", "SYSTEM TIME"))
        self.val_lat.setText(_translate("MainWindow", "10.1234567"))
        self.lb_lat.setText(_translate("MainWindow", "LATITUDE"))
        self.val_lon.setText(_translate("MainWindow", "100.3224358"))
        self.lb_lon.setText(_translate("MainWindow", "LONGITUDE"))
        self.val_gps_alt.setText(_translate("MainWindow", "123.25"))
        self.lb_gps_alt.setText(_translate("MainWindow", "GPS ALTITUDE (m)"))
        self.lb_int_temp.setText(_translate("MainWindow", "INT TEMPERATURE"))
        self.val_ext_temp.setText(_translate("MainWindow", "-12.35"))
        self.val_int_temp.setText(_translate("MainWindow", "36.75"))
        self.val_vel.setText(_translate("MainWindow", "20.34"))
        self.lb_vel.setText(_translate("MainWindow", "MPXV VELOCITY"))
        self.val_hum.setText(_translate("MainWindow", "84.52"))
        self.lb_bar_alt.setText(_translate("MainWindow", "BAR ALTITUDE (m)"))
        self.lb_hum.setText(_translate("MainWindow", "INT HUMIDITY"))
        self.lb_ext_temp.setText(_translate("MainWindow", "EXT TEMPERATURE"))
        self.val_bar_alt.setText(_translate("MainWindow", "123.42"))
        self.pushButton.setText(_translate("MainWindow", "CONNECT"))
        self.pushButton_2.setText(_translate("MainWindow", "DISCONNECT"))
        self.pushButton_3.setText(_translate("MainWindow", "REFRESH"))
        self.val_accx.setText(_translate("MainWindow", "433"))
        self.lb_accz.setText(_translate("MainWindow", "ACC_Z"))
        self.val_gyrx.setText(_translate("MainWindow", "84.52"))
        self.lb_gyrx.setText(_translate("MainWindow", "ORIENT_X"))
        self.val_accz.setText(_translate("MainWindow", "-12.35"))
        self.lb_accx.setText(_translate("MainWindow", "ACC_X"))
        self.lb_gyry.setText(_translate("MainWindow", "ORIENT_Y"))
        self.lb_accy.setText(_translate("MainWindow", "ACC_Y"))
        self.val_gyry.setText(_translate("MainWindow", "20.34"))
        self.lb_gyrz.setText(_translate("MainWindow", "ORIENT_Z"))
        self.val_accy.setText(_translate("MainWindow", "36.75"))
        self.val_gyrz.setText(_translate("MainWindow", "123.42"))
        self.lb_subtitle_2.setText(_translate("MainWindow", "CHANNEL 2 (868 MHz), BAUD 9600 ONLY!"))
        self.val_pkg_2.setText(_translate("MainWindow", "123"))
        self.lb_pkg_2.setText(_translate("MainWindow", "PACKET COUNT"))
        self.lb_sys_time_2.setText(_translate("MainWindow", "SYSTEM TIME"))
        self.val_sys_time_2.setText(_translate("MainWindow", "10:24:39"))
        self.lb_lon_2.setText(_translate("MainWindow", "LONGITUDE"))
        self.val_lon_2.setText(_translate("MainWindow", "100.3224358"))
        self.val_lat_2.setText(_translate("MainWindow", "10.1234567"))
        self.lb_lat_2.setText(_translate("MainWindow", "LATITUDE"))
        self.lb_pm103.setText(_translate("MainWindow", "PM10 NO.3"))
        self.val_pm101.setText(_translate("MainWindow", "84.52"))
        self.lb_pm102.setText(_translate("MainWindow", "PM10 NO.2"))
        self.val_pm103.setText(_translate("MainWindow", "123.42"))
        self.val_102.setText(_translate("MainWindow", "20.34"))
        self.lb_pm101.setText(_translate("MainWindow", "PM10 NO.1"))
        self.lb_ext_temp_2.setText(_translate("MainWindow", "EXT TEMPERATURE"))
        self.val_ext_temp_2.setText(_translate("MainWindow", "-12.35"))
        self.lb_subtitle_3.setText(_translate("MainWindow", "CHANNEL 3 (915 MHz), BAUD 9600 ONLY!"))
        self.lb_pkg_3.setText(_translate("MainWindow", "PACKET COUNT"))
        self.val_pkg_3.setText(_translate("MainWindow", "123"))
        self.lb_sys_time_3.setText(_translate("MainWindow", "SYSTEM TIME"))
        self.val_sys_time_3.setText(_translate("MainWindow", "10:24:39"))
        self.lb_gps_alt_2.setText(_translate("MainWindow", "GPS ALTITUDE (m)"))
        self.val_gps_alt_2.setText(_translate("MainWindow", "123.25"))
        self.lb_bar_alt_2.setText(_translate("MainWindow", "BAR ALTITUDE (m)"))
        self.val_bar_alt_2.setText(_translate("MainWindow", "123.42"))
        self.lb_vol.setText(_translate("MainWindow", "BATT. VOL. (mV)"))
        self.val_vol.setText(_translate("MainWindow", "123.42"))
        self.pushButton_4.setText(_translate("MainWindow", "OPEN GRAPH"))
        self.val_freq_2.setText(_translate("MainWindow", "433"))
        self.lb_freq_2.setText(_translate("MainWindow", "FREQUENCY (MHz)"))
        self.val_freq_3.setText(_translate("MainWindow", "433"))
        self.lb_freq_3.setText(_translate("MainWindow", "FREQUENCY (MHz)"))
        self.val_lon_3.setText(_translate("MainWindow", "100.3224358"))
        self.lb_lat_3.setText(_translate("MainWindow", "LATITUDE"))
        self.lb_lon_3.setText(_translate("MainWindow", "LONGITUDE"))
        self.val_lat_3.setText(_translate("MainWindow", "10.1234567"))
        self.val_sys_time_4.setText(_translate("MainWindow", "10:24:39"))
        self.lb_sys_time_4.setText(_translate("MainWindow", "CURRENT TIME (PC)"))
        self.val_sys_time_5.setText(_translate("MainWindow", "10:24:39"))
        self.lb_sys_time_5.setText(_translate("MainWindow", "TIME ELAPSED"))
        self.pushButton_5.setText(_translate("MainWindow", "CLEAR GRAPH"))
        self.pushButton_6.setText(_translate("MainWindow", "FN1"))
        self.pushButton_7.setText(_translate("MainWindow", "FN2"))
        self.pushButton_8.setText(_translate("MainWindow", "FN3"))
        self.pushButton_9.setText(_translate("MainWindow", "FN4"))
        self.pushButton_10.setText(_translate("MainWindow", "FN5"))
        self.lb_lon_4.setText(_translate("MainWindow", "PC LONGITUDE"))
        self.val_lon_4.setText(_translate("MainWindow", "100.3224358"))
        self.val_lat_4.setText(_translate("MainWindow", "10.1234567"))
        self.lb_lat_4.setText(_translate("MainWindow", "PC LATITUDE"))
        self.lb_adjroll.setText(_translate("MainWindow", "ADJUST ROLL"))
        self.lb_adjalt.setText(_translate("MainWindow", "ADJUST ALTITUDE"))
        self.lb_adjplane.setText(_translate("MainWindow", "ADJUST PLANAR"))
        self.lb_sys_time_6.setText(_translate("MainWindow", "GROUND DISTANCE"))
        self.lb_sys_time_7.setText(_translate("MainWindow", "LINE OF SIGHT"))
        self.val_xlos.setText(_translate("MainWindow", "3569.65"))
        self.val_xgd.setText(_translate("MainWindow", "2876.44"))
        self.val_gaz.setText(_translate("MainWindow", "123.42"))
        self.lb_vol_2.setText(_translate("MainWindow", "AZIMUTH"))
        self.val_gel.setText(_translate("MainWindow", "123.42"))
        self.lb_vol_3.setText(_translate("MainWindow", "ELEVATION"))
        self.val_ghd.setText(_translate("MainWindow", "123.42"))
        self.lb_vol_4.setText(_translate("MainWindow", "HEADING"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

